version: '3'

services:
  topo-cpython:
    build:
      context: .
      args:
      - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
      - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/topo-cpython:0.0.0
    volumes:
      - ./topo/:/opt/topo/topo/
      - ./tests/:/opt/topo/tests/
      - ./README.md:/opt/topo/README.md
      - ./setup.py:/opt/topo/setup.py
      - ./setup.cfg:/opt/topo/setup.cfg
    entrypoint: python3
    command: setup.py test
